[package]
name = "winrt"
version = "0.1.0"
authors = ["Patrick Reisert"]

[dependencies]
winapi = "0.2.7"
runtimeobject-sys = "0.0.1"
ole32-sys = "0.2.0"
oleaut32-sys = "0.0.1"

[features]
nightly = []